from dotenv import load_dotenv
import os

load_dotenv()

DB_USERNAME = os.getenv("DB_USERNAME")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT")
DB_NAME = os.getenv("DB_NAME")

SPOTIPY_CLIENT_ID = os.getenv("SPOTIPY_CLIENT_ID")
SPOTIPY_CLIENT_SECRET = os.getenv("SPOTIPY_CLIENT_SECRET")
SPOTIPY_REDIRECT_URI = os.getenv("SPOTIPY_REDIRECT_URI")
SPOTIPY_SCOPE = os.getenv("SPOTIPY_SCOPE")

SESSION_COOKIE_NAME = os.getenv("SESSION_COOKIE_NAME")
SESSION_USER_EXPIRE_TIME = os.getenv("SESSION_USER_EXPIRE_TIME")
SESSION_OBJECT_EXPIRE_TIME = os.getenv("SESSION_OBJECT_TIME")