from dotenv import load_dotenv
import os

load_dotenv()

DB_USERNAME = os.getenv("DB_USERNAME")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT")
DB_NAME = os.getenv("DB_NAME")
DB_SCRAPE_TIME_DELTA_DAYS = os.getenv("DB_SCRAPE_TIME_DELTA_DAYS")

REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = os.getenv("REDIS_PORT")

SPOTIPY_CLIENT_ID = os.getenv("SPOTIPY_CLIENT_ID")
SPOTIPY_CLIENT_SECRET = os.getenv("SPOTIPY_CLIENT_SECRET")
SPOTIPY_REDIRECT_URI = os.getenv("SPOTIPY_REDIRECT_URI")
SPOTIPY_SCOPE = os.getenv("SPOTIPY_SCOPE")

SESSION_COOKIE_NAME = os.getenv("SESSION_COOKIE_NAME")
SESSION_USER_EXPIRE_TIME = os.getenv("SESSION_USER_EXPIRE_TIME")
CACHE_OBJECT_TTL = os.getenv("CACHE_OBJECT_TTL")

DEC_PREC = int(os.getenv("DEC_PREC"))